# Generated by Django 3.2.8 on 2021-12-16 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='isarty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='ishistoric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='ispsychology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='issocial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='isstory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
