# Generated by Django 3.2.8 on 2021-12-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isscientific',
            field=models.BooleanField(default=False),
        ),
    ]
