# Generated by Django 3.2.8 on 2021-12-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(default='مرد', max_length=10, null=True),
        ),
    ]
