# Generated by Django 3.2.10 on 2021-12-18 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=8),
        ),
    ]
