# Generated by Django 3.2.10 on 2021-12-19 00:54

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='a2.jpg', null=True, upload_to=account.models.upload_location),
        ),
    ]
