# Generated by Django 3.2.9 on 2021-12-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='authors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='bookAvatar',
            field=models.FileField(blank=True, upload_to='book/image'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
