# Generated by Django 3.2.8 on 2021-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211126_0126'),
        ('book', '0002_auto_20211202_0639'),
    ]

    operations = [
    ]
