# Generated by Django 4.0 on 2021-12-17 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_image'),
        ('book', '0007_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='book.addbook'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='account.account'),
        ),
    ]
