# Generated by Django 4.0 on 2021-12-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_image'),
        ('book', '0008_alter_favourite_book_alter_favourite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favourite',
        ),
        migrations.AddField(
            model_name='addbook',
            name='favourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addbook',
            name='favourite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites_book', to='book.addbook'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_favourites_user', to='account.account'),
        ),
    ]
