# Generated by Django 4.0 on 2021-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_addbook_favourite_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='favourite_count',
            field=models.IntegerField(default=0),
        ),
    ]
