# Generated by Django 3.2.10 on 2022-01-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_rename_user_reply_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
