# Generated by Django 3.2.10 on 2022-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20220123_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='isread',
        ),
        migrations.AddField(
            model_name='notification',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
