from django.db import models
from PIL import Image


class AddBook(models.Model):
    TOPIC_CHOICES = (
        ('Art')
        ('biography')
        ('diary')
        ('Business')
        ('children')
        ('Religious')
        ('Classic')
        ('Comics')
        ('Cookbooks')
        ('E-books')
        ('Fantasy')
        ('Story')
        ('Graphic novels')
        ('Historical myths')
        ('Date')
        ('Panic')
        ('the memories')
        ('Music')
        ('Mystery')
        ('Non-fiction')
        ('Poetry')
        ('Psychology')
        ('love story')
        ('Science')
        ('Science Fiction')
        ('Self-help')
        ('sports')
        ('horrific')
        ('travel')
        ('Young adults')
        ('More genres')

    )
    selectedTopic = models.CharField(max_length=3, choices=TOPIC_CHOICES, null=True)
    title = models.CharField(max_length=100)
    Description = models.CharField(max_length=100, null=True)
    bookAvatar = models.FileField(upload_to="book/image")
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()